/* generated by pull.js */
const manifest = {
    "name": "Customizable block font",
    "description": "Changes the font of blocks and dropdowns. The Input is case-sensitive and works if it's in Google-Fonts or in the font dropdown menu in the Costume Editor.",
    "credits": [
      {
        "name": "MrIncredibleMaker",
        "link": "https://scratch.mit.edu/users/MrIncredibleMakerZe/"
      },
    ],
    "tags": [
      "theme",
      "new",
      "dinosaurmod",
      "beta"
    ],
    "enabledByDefault": false,
    "settings": [
      {
        "dynamic": true,
        "name": "Font Name",
        "id": "blockFont",
        "type": "text",
        "default": ""
      }
    ],
    "userstyles": [],
    "userscripts": [
      {
        "url": "userscript.js"
      }
    ],
    "info": [
      {
        "type": "notice",
        "text": "Depending on the font, the width of the letters/symbols in the font can overlap and make the block look weird.",
        "id": "fontWarning"
      }
    ],
    "dynamicDisable": true
  };
  export default manifest;