/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./undo-redo-buttons.css";
export const resources = {
  "userscript.js": _js,
  "undo-redo-buttons.css": _css
};
