/* generated by pull.js */
const manifest = {
    "name": "Custom website font (Scratch Tools)",
    "description": "Changes the font of the site. The Input is case-sensitive and works if it's in Google-Fonts or in the font dropdown menu in the Costume Editor.",
    "credits": [
      {
        "name": "Scratchfangs",
        "link": "https://scratch.mit.edu/users/Scratchfangs/"
      },
      {
        "name": "devxan",
        "link": "https://github.com/devxan"
      },
      {
        "name": "rgantzos",
        "link": "https://scratch.mit.edu/users/rgantzos/"
      }
    ],
    "tags": [
      "theme",
      "new"
    ],
    "enabledByDefault": false,
    "settings": [
      {
        "dynamic": true,
        "name": "Font Name",
        "id": "webFont",
        "type": "text",
        "default": ""
      }
    ],
    "userstyles": [],
    "userscripts": [
      {
        "url": "userscript.js"
      }
    ],
    "dynamicDisable": true
  };
  export default manifest;